name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Install System Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          pkg-config \
          libgl1-mesa-dev \
          libx11-dev \
          libxxf86vm-dev \
          libxi-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxcursor-dev \
          libglu1-mesa-dev \
          xorg-dev

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Dependencies
      run: |
        go mod tidy
        go mod download

    - name: Build
      run: go build -v ./...

    - name: Test
      run: |
        go test -v ./...
        if [ $? -ne 0 ]; then
          exit 1
        fi
